//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchDBRESTClientopg6.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fangst", Namespace="http://schemas.datacontract.org/2004/07/FishWebserviceDBASWopg6.Model")]
    [System.SerializableAttribute()]
    public partial class Fangst : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VeagtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Art {
            get {
                return this.ArtField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtField, value) != true)) {
                    this.ArtField = value;
                    this.RaisePropertyChanged("Art");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sted {
            get {
                return this.StedField;
            }
            set {
                if ((object.ReferenceEquals(this.StedField, value) != true)) {
                    this.StedField = value;
                    this.RaisePropertyChanged("Sted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Uge {
            get {
                return this.UgeField;
            }
            set {
                if ((this.UgeField.Equals(value) != true)) {
                    this.UgeField = value;
                    this.RaisePropertyChanged("Uge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Veagt {
            get {
                return this.VeagtField;
            }
            set {
                if ((this.VeagtField.Equals(value) != true)) {
                    this.VeagtField = value;
                    this.RaisePropertyChanged("Veagt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFishServiceDB")]
    public interface IFishServiceDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/GetCatchesDB", ReplyAction="http://tempuri.org/IFishServiceDB/GetCatchesDBResponse")]
        CatchDBRESTClientopg6.ServiceReference1.Fangst[] GetCatchesDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/GetCatchesDB", ReplyAction="http://tempuri.org/IFishServiceDB/GetCatchesDBResponse")]
        System.Threading.Tasks.Task<CatchDBRESTClientopg6.ServiceReference1.Fangst[]> GetCatchesDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/GetWeekCatchDB", ReplyAction="http://tempuri.org/IFishServiceDB/GetWeekCatchDBResponse")]
        CatchDBRESTClientopg6.ServiceReference1.Fangst[] GetWeekCatchDB(int uge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/GetWeekCatchDB", ReplyAction="http://tempuri.org/IFishServiceDB/GetWeekCatchDBResponse")]
        System.Threading.Tasks.Task<CatchDBRESTClientopg6.ServiceReference1.Fangst[]> GetWeekCatchDBAsync(int uge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/AddCatchDB", ReplyAction="http://tempuri.org/IFishServiceDB/AddCatchDBResponse")]
        void AddCatchDB(string navn, string art, double vaegt, string sted, int uge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFishServiceDB/AddCatchDB", ReplyAction="http://tempuri.org/IFishServiceDB/AddCatchDBResponse")]
        System.Threading.Tasks.Task AddCatchDBAsync(string navn, string art, double vaegt, string sted, int uge);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFishServiceDBChannel : CatchDBRESTClientopg6.ServiceReference1.IFishServiceDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FishServiceDBClient : System.ServiceModel.ClientBase<CatchDBRESTClientopg6.ServiceReference1.IFishServiceDB>, CatchDBRESTClientopg6.ServiceReference1.IFishServiceDB {
        
        public FishServiceDBClient() {
        }
        
        public FishServiceDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FishServiceDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FishServiceDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FishServiceDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CatchDBRESTClientopg6.ServiceReference1.Fangst[] GetCatchesDB() {
            return base.Channel.GetCatchesDB();
        }
        
        public System.Threading.Tasks.Task<CatchDBRESTClientopg6.ServiceReference1.Fangst[]> GetCatchesDBAsync() {
            return base.Channel.GetCatchesDBAsync();
        }
        
        public CatchDBRESTClientopg6.ServiceReference1.Fangst[] GetWeekCatchDB(int uge) {
            return base.Channel.GetWeekCatchDB(uge);
        }
        
        public System.Threading.Tasks.Task<CatchDBRESTClientopg6.ServiceReference1.Fangst[]> GetWeekCatchDBAsync(int uge) {
            return base.Channel.GetWeekCatchDBAsync(uge);
        }
        
        public void AddCatchDB(string navn, string art, double vaegt, string sted, int uge) {
            base.Channel.AddCatchDB(navn, art, vaegt, sted, uge);
        }
        
        public System.Threading.Tasks.Task AddCatchDBAsync(string navn, string art, double vaegt, string sted, int uge) {
            return base.Channel.AddCatchDBAsync(navn, art, vaegt, sted, uge);
        }
    }
}
